version: "3.7"
services:
  app:
    build:
      args:
        user: devuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sample
    container_name: sample-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sample

  db-mysql:
    image: mysql:5.7
    container_name: sample-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "6603:3306"
    volumes:
      - ./init-files/mysql:/docker-entrypoint-initdb.d
    networks:
      - sample

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sample-phpmyadmin
    environment:
      PMA_HOST: db-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      - sample
    depends_on:
      - db-mysql
    ports:
      - 8001:80

  nginx:
    image: nginx:alpine
    container_name: sample-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sample

networks:
  sample:
    driver: bridge
volumes:
  dbdata: